### PR TITLE
Update login to use MOT keycloak and update BE and FE to accomodate l…

### PR DESCRIPTION
**Pull request by karthikktamilmani-freshworks**
…ogin with IDIR

### CODE REVIEW

**Comment by leon-fw** [comment]
Hey Karthikk, trying to make this run on my end, here's what I ran into so far:
1) I don't think "@nestjs/passport" and "passport-jwt" were added into yarn/package.json, had to install them manually using yarn add ". in the server folder, otherwise the server docker was complaining that "module is not found".

2) I encountered this while trying to log in, do you happen to know what this error might be related to? Happens right after you click "login" on localhost:3000:
image


Thanks in advance!

**Comment by leon-fw** [comment]
> Hey Karthikk, trying to make this run on my end, here's what I ran into so far:
> 
> 1. I don't think "@nestjs/passport" and "passport-jwt" were added into yarn/package.json, had to install them manually using yarn add ". in the server folder, otherwise the server docker was complaining that "module is not found".
> 2. I encountered this while trying to log in, do you happen to know what this error might be related to? Happens right after you click "login" on localhost:3000:
> 
> image
> 
> Thanks in advance!

Pressing login redirects you to

```
https://dev.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/auth?client_id=ed-9154-dev-4226&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Flogin&state=1635c8d1-2ea7-416a-a6d3-6cdee6376f82&response_mode=fragment&response_type=code&scope=openid&nonce=c16aed2d-c8d4-4fd1-a498-63a42b54d906&kc_idp_hint=idir&code_challenge=1FcKbe_QuzPD1rK1K5xHHjJKkD7bd5qtVAEUzFBCznw&code_challenge_method=S256
```

 by the way, and that's the page where I see the error.

**Comment by karthikktamilmani-freshworks** [comment]
@leon-fw The PR has the yarn.lock which contains all the missing dependencies that you stated. So, the possible cause for the issue would be that your docker is not rebuilt.

As far as the issue with redirect URI, I've pasted the updated envs for server and client in the Wiki folder in our channel. Updating those values should fix the issue

**Comment by leon-fw** [comment]
> 

Oh, so that's what I was missing, thank you! I put the .env stuff in and now it redirects me here, as expected:
image

Logged in using IDIR, all working as expected so far. Feel free to merge!

**Pull request merged**
